// <auto-generated />
using System;
using ECommerce.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.MVC.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20230907080425_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Entity.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MasterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Automotive",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5397),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Automotive description.",
                            MasterID = new Guid("b5af9053-9583-498e-b1f2-c4761b092766"),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Jewelery",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5495),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Jewelery description.",
                            MasterID = new Guid("4d4f11af-6fb8-49f0-9023-1f45cd160cea"),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Clothing",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5498),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Clothing description.",
                            MasterID = new Guid("dfd9a2d6-36d8-46d6-a117-8bf0b303b7d8"),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Baby",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5500),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Baby description.",
                            MasterID = new Guid("a5531b3c-02f7-4668-bce6-4c9c988bee03"),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Outdoors",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5502),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Outdoors description.",
                            MasterID = new Guid("9073b865-3d3d-473b-8daf-34c071b88546"),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Toys",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5517),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Toys description.",
                            MasterID = new Guid("3edb5b0c-797e-493c-b026-e190e2503d95"),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Beauty",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5519),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Beauty description.",
                            MasterID = new Guid("7c23281b-c613-46e5-be57-da242f87fc8f"),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Tools",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5521),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tools description.",
                            MasterID = new Guid("7b6499fa-7ab9-4e82-bc8e-3aee0d966eab"),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Garden",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5523),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Garden description.",
                            MasterID = new Guid("6a3ee68c-9660-4a7a-a7c0-44b3bd2b19c6"),
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Games",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5526),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Games description.",
                            MasterID = new Guid("32886faa-0154-42af-8f84-9398b8b35ba9"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("MasterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5665),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("ad462075-38a6-4c29-99de-b6f2c613f5e2"),
                            ProductName = "Tasty Rubber Soap",
                            Status = 0,
                            UnitPrice = 834.15m,
                            UnitsInStock = (short)8422
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5793),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("5180a1a1-2320-4e11-a1fe-e97ed1283cb4"),
                            ProductName = "Handmade Rubber Chips",
                            Status = 0,
                            UnitPrice = 376.97m,
                            UnitsInStock = (short)2581
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5812),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("ca679140-dd89-4d38-b97c-fd23e240f944"),
                            ProductName = "Handcrafted Steel Salad",
                            Status = 0,
                            UnitPrice = 450.87m,
                            UnitsInStock = (short)4755
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5832),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("eef29644-22d3-4af1-9c84-8f47d08a5a14"),
                            ProductName = "Gorgeous Granite Hat",
                            Status = 0,
                            UnitPrice = 671.35m,
                            UnitsInStock = (short)4245
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5849),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("1c113ed1-b471-4cc1-b4a1-d0c35e35851b"),
                            ProductName = "Unbranded Fresh Chicken",
                            Status = 0,
                            UnitPrice = 238.87m,
                            UnitsInStock = (short)3413
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5866),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("af5a5305-b685-4118-b0da-daf57b2f2855"),
                            ProductName = "Intelligent Metal Pizza",
                            Status = 0,
                            UnitPrice = 410.09m,
                            UnitsInStock = (short)2072
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5883),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("a13fdc8c-6f07-4f8d-8eaa-bef96ec8ba1a"),
                            ProductName = "Ergonomic Soft Mouse",
                            Status = 0,
                            UnitPrice = 917.85m,
                            UnitsInStock = (short)4562
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5928),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Rustic",
                            MasterID = new Guid("44532397-d358-46fb-a0fd-c644f5f4eb7b"),
                            ProductName = "Small Plastic Shoes",
                            Status = 0,
                            UnitPrice = 622.93m,
                            UnitsInStock = (short)8314
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5944),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("5a08ed01-f2eb-41df-81b3-9642d109f220"),
                            ProductName = "Tasty Wooden Tuna",
                            Status = 0,
                            UnitPrice = 336.61m,
                            UnitsInStock = (short)4319
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5962),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Rustic",
                            MasterID = new Guid("fd70e8dd-2260-4aee-963c-62e520a1585b"),
                            ProductName = "Intelligent Metal Table",
                            Status = 0,
                            UnitPrice = 334.88m,
                            UnitsInStock = (short)2563
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5978),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("af969825-c826-4b66-be30-4e33e6512c9f"),
                            ProductName = "Intelligent Steel Tuna",
                            Status = 0,
                            UnitPrice = 668.34m,
                            UnitsInStock = (short)3569
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(5994),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("5fffe756-0062-4847-af5c-5eec96cddf0a"),
                            ProductName = "Practical Soft Bacon",
                            Status = 0,
                            UnitPrice = 519.23m,
                            UnitsInStock = (short)6719
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6009),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("d365b431-c513-42ce-be81-25e5b91dcd7c"),
                            ProductName = "Handcrafted Soft Pants",
                            Status = 0,
                            UnitPrice = 757.20m,
                            UnitsInStock = (short)7820
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6024),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Rustic",
                            MasterID = new Guid("8adb4869-ae4a-450c-88cd-f3bf9c965478"),
                            ProductName = "Handcrafted Steel Salad",
                            Status = 0,
                            UnitPrice = 261.81m,
                            UnitsInStock = (short)7004
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6038),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("70e95f2b-7280-43d8-8583-b7f88d6dcb95"),
                            ProductName = "Intelligent Frozen Pizza",
                            Status = 0,
                            UnitPrice = 284.80m,
                            UnitsInStock = (short)7458
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6052),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("0a0fd4e1-1663-4cb3-8b66-742d26287013"),
                            ProductName = "Practical Cotton Pizza",
                            Status = 0,
                            UnitPrice = 831.34m,
                            UnitsInStock = (short)4703
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6092),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("fe4dfe5f-cb72-43a9-b769-7e3ffd9205b7"),
                            ProductName = "Rustic Fresh Sausages",
                            Status = 0,
                            UnitPrice = 578.52m,
                            UnitsInStock = (short)3462
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6109),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("dbd08080-8ee4-4d92-a6cf-17ea8f745eef"),
                            ProductName = "Incredible Soft Towels",
                            Status = 0,
                            UnitPrice = 961.89m,
                            UnitsInStock = (short)2631
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6123),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("b619e6bc-f1da-46b0-9d42-d9712ab0d97b"),
                            ProductName = "Incredible Metal Fish",
                            Status = 0,
                            UnitPrice = 921.47m,
                            UnitsInStock = (short)5736
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6139),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("125e8356-14c5-4048-8335-776395b1855f"),
                            ProductName = "Licensed Cotton Keyboard",
                            Status = 0,
                            UnitPrice = 775.43m,
                            UnitsInStock = (short)5111
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6153),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("f04d7d51-222e-44f2-8013-93e5b96af6f6"),
                            ProductName = "Handmade Rubber Chips",
                            Status = 0,
                            UnitPrice = 743.01m,
                            UnitsInStock = (short)9692
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6167),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("59be86aa-445a-47e1-bf0f-bea5dcba315a"),
                            ProductName = "Refined Metal Tuna",
                            Status = 0,
                            UnitPrice = 37.08m,
                            UnitsInStock = (short)4701
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6181),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("0fb70d8d-afe9-4be2-bc88-334b09cf489a"),
                            ProductName = "Sleek Wooden Table",
                            Status = 0,
                            UnitPrice = 635.19m,
                            UnitsInStock = (short)4923
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6195),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("0c909591-754b-493c-8509-c2484eb0d65c"),
                            ProductName = "Rustic Fresh Pizza",
                            Status = 0,
                            UnitPrice = 169.13m,
                            UnitsInStock = (short)3001
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6208),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("cfb3f6d5-8230-48e9-a7fc-1a7e8a4d50d3"),
                            ProductName = "Handmade Rubber Shirt",
                            Status = 0,
                            UnitPrice = 155.65m,
                            UnitsInStock = (short)2824
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6223),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("0aafca1d-dbdc-41d8-85ac-9c0b0e8e1570"),
                            ProductName = "Ergonomic Concrete Gloves",
                            Status = 0,
                            UnitPrice = 972.32m,
                            UnitsInStock = (short)6197
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6266),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("916f3adf-c538-4c30-b430-cab7545a0af6"),
                            ProductName = "Intelligent Granite Sausages",
                            Status = 0,
                            UnitPrice = 223.62m,
                            UnitsInStock = (short)1509
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6282),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("f27e9c47-c0f5-42fa-9fba-410680a2e703"),
                            ProductName = "Fantastic Soft Bike",
                            Status = 0,
                            UnitPrice = 854.90m,
                            UnitsInStock = (short)1984
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6295),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("f8eef3cd-ebb9-4c17-9512-8d30df9dbf08"),
                            ProductName = "Sleek Concrete Salad",
                            Status = 0,
                            UnitPrice = 945.97m,
                            UnitsInStock = (short)8829
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6309),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("45d30fbb-556b-4ee1-b79d-93736924453d"),
                            ProductName = "Tasty Metal Chips",
                            Status = 0,
                            UnitPrice = 569.90m,
                            UnitsInStock = (short)4698
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6322),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("f8d15d92-285f-4d09-9399-406678330558"),
                            ProductName = "Gorgeous Soft Salad",
                            Status = 0,
                            UnitPrice = 366.16m,
                            UnitsInStock = (short)4221
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6337),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("fb7f200d-8c03-43c6-b5fb-1be58e84ca21"),
                            ProductName = "Gorgeous Rubber Cheese",
                            Status = 0,
                            UnitPrice = 309.22m,
                            UnitsInStock = (short)8626
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6352),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("670aea4f-af47-46db-8cfc-f75869968c32"),
                            ProductName = "Rustic Metal Bike",
                            Status = 0,
                            UnitPrice = 371.40m,
                            UnitsInStock = (short)6766
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6367),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("2453dc1c-02ec-44f3-b933-2122ce3227af"),
                            ProductName = "Licensed Wooden Computer",
                            Status = 0,
                            UnitPrice = 11.61m,
                            UnitsInStock = (short)5448
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6381),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("3c92c551-1f26-4a39-9c5e-ea9d42543042"),
                            ProductName = "Incredible Frozen Salad",
                            Status = 0,
                            UnitPrice = 355.64m,
                            UnitsInStock = (short)3627
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6437),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("fec77b29-c953-43c0-b4bb-8c66037be46b"),
                            ProductName = "Fantastic Rubber Pants",
                            Status = 0,
                            UnitPrice = 600.68m,
                            UnitsInStock = (short)2955
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6454),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("c2333471-ec8b-49cd-aea3-c64aea783569"),
                            ProductName = "Ergonomic Fresh Bacon",
                            Status = 0,
                            UnitPrice = 692.74m,
                            UnitsInStock = (short)2884
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6468),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("9dad8f36-4602-4c05-85e9-e95a1e9f1c4b"),
                            ProductName = "Intelligent Plastic Gloves",
                            Status = 0,
                            UnitPrice = 341.38m,
                            UnitsInStock = (short)617
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6482),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("31e4c99b-f315-42c2-9031-1fb6fd6869e4"),
                            ProductName = "Unbranded Granite Shoes",
                            Status = 0,
                            UnitPrice = 177.98m,
                            UnitsInStock = (short)7523
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6495),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("4ccd852f-3813-4508-964a-8d302cfefded"),
                            ProductName = "Fantastic Wooden Computer",
                            Status = 0,
                            UnitPrice = 947.69m,
                            UnitsInStock = (short)4629
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6510),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("cff8f69b-79d4-4b08-a033-d73137ff4fb6"),
                            ProductName = "Gorgeous Wooden Hat",
                            Status = 0,
                            UnitPrice = 663.80m,
                            UnitsInStock = (short)6408
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6523),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("e1ec302b-5f9a-49f8-8133-4ba824b38a29"),
                            ProductName = "Intelligent Steel Soap",
                            Status = 0,
                            UnitPrice = 790.40m,
                            UnitsInStock = (short)9205
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6537),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("411b90c6-c75f-422f-b017-53915dfef698"),
                            ProductName = "Handcrafted Cotton Car",
                            Status = 0,
                            UnitPrice = 349.18m,
                            UnitsInStock = (short)3982
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6554),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("17761335-441e-4c4a-93b1-d406093276b7"),
                            ProductName = "Awesome Metal Tuna",
                            Status = 0,
                            UnitPrice = 603.43m,
                            UnitsInStock = (short)3015
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6568),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("256ef471-3bf2-4d3d-98ef-1babdf3e80e6"),
                            ProductName = "Incredible Granite Car",
                            Status = 0,
                            UnitPrice = 814.27m,
                            UnitsInStock = (short)4359
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6607),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("0e5b1a4d-08ca-4d72-8976-f69d17749ef6"),
                            ProductName = "Incredible Rubber Cheese",
                            Status = 0,
                            UnitPrice = 955.08m,
                            UnitsInStock = (short)4145
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6622),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("664300f8-226e-4587-81db-f75939ab2311"),
                            ProductName = "Gorgeous Cotton Hat",
                            Status = 0,
                            UnitPrice = 21.95m,
                            UnitsInStock = (short)7500
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6636),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("dadb37d5-4716-4138-a716-96fae90b8c8a"),
                            ProductName = "Licensed Steel Bacon",
                            Status = 0,
                            UnitPrice = 791.64m,
                            UnitsInStock = (short)4606
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6650),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("09be7645-d31a-49de-8e73-b48bfc194061"),
                            ProductName = "Unbranded Granite Pizza",
                            Status = 0,
                            UnitPrice = 161.00m,
                            UnitsInStock = (short)316
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6664),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("a16cdf52-e579-4d63-bfa9-6e1c21d286c1"),
                            ProductName = "Incredible Soft Chicken",
                            Status = 0,
                            UnitPrice = 611.98m,
                            UnitsInStock = (short)9928
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6677),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("e964b19e-9e84-4aab-9363-d20ccdbe493c"),
                            ProductName = "Intelligent Fresh Chair",
                            Status = 0,
                            UnitPrice = 122.24m,
                            UnitsInStock = (short)9018
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6693),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handmade",
                            MasterID = new Guid("44623044-a047-4ca8-87b8-44a5d1390dfd"),
                            ProductName = "Unbranded Rubber Table",
                            Status = 0,
                            UnitPrice = 995.81m,
                            UnitsInStock = (short)4928
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6706),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("2e202ac7-f522-4766-b922-f3482498add1"),
                            ProductName = "Licensed Cotton Bacon",
                            Status = 0,
                            UnitPrice = 701.53m,
                            UnitsInStock = (short)6722
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6719),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("fa6daee5-8e43-4119-9078-8968e1654dd6"),
                            ProductName = "Intelligent Metal Hat",
                            Status = 0,
                            UnitPrice = 778.37m,
                            UnitsInStock = (short)2868
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6733),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("d27cf2ae-187d-479c-8146-a033f0d8ab26"),
                            ProductName = "Intelligent Rubber Gloves",
                            Status = 0,
                            UnitPrice = 257.31m,
                            UnitsInStock = (short)5406
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6771),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("d30270e9-1c70-4cee-b512-7bad89bfdbe2"),
                            ProductName = "Awesome Frozen Shoes",
                            Status = 0,
                            UnitPrice = 310.98m,
                            UnitsInStock = (short)4196
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6785),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("91ec4a8e-1708-4c48-b61b-61ec117c82ba"),
                            ProductName = "Refined Concrete Chips",
                            Status = 0,
                            UnitPrice = 398.26m,
                            UnitsInStock = (short)1880
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6799),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("bb2c3a43-34db-4f9c-9539-c97cd336539d"),
                            ProductName = "Incredible Fresh Cheese",
                            Status = 0,
                            UnitPrice = 986.21m,
                            UnitsInStock = (short)4843
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6812),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("b14fcf72-d335-48c8-a4e0-72792ca5f661"),
                            ProductName = "Gorgeous Cotton Mouse",
                            Status = 0,
                            UnitPrice = 658.54m,
                            UnitsInStock = (short)5791
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6827),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("baa2beb9-7803-415a-918c-49894b3ad07e"),
                            ProductName = "Practical Cotton Cheese",
                            Status = 0,
                            UnitPrice = 405.92m,
                            UnitsInStock = (short)3794
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6842),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("8d6b482f-c236-40ca-aef5-bd7672faa2d2"),
                            ProductName = "Rustic Soft Table",
                            Status = 0,
                            UnitPrice = 553.00m,
                            UnitsInStock = (short)4722
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6855),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("ef44af75-f04e-448d-8518-dbca487971ab"),
                            ProductName = "Incredible Steel Bike",
                            Status = 0,
                            UnitPrice = 306.50m,
                            UnitsInStock = (short)2492
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6869),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("decfa5c5-bc63-4220-8a1e-485f98190ff1"),
                            ProductName = "Handmade Soft Computer",
                            Status = 0,
                            UnitPrice = 104.78m,
                            UnitsInStock = (short)4491
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6883),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("7630ac29-b9d7-4214-82d2-b53aa02eb998"),
                            ProductName = "Tasty Frozen Salad",
                            Status = 0,
                            UnitPrice = 966.54m,
                            UnitsInStock = (short)928
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6897),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("50911989-92c4-4e19-8521-bf94b0baa99b"),
                            ProductName = "Generic Soft Bacon",
                            Status = 0,
                            UnitPrice = 121.98m,
                            UnitsInStock = (short)9861
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6937),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("b6975f12-0377-45b9-9446-2a742f46d8e9"),
                            ProductName = "Gorgeous Steel Shirt",
                            Status = 0,
                            UnitPrice = 913.04m,
                            UnitsInStock = (short)3214
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6951),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("fe789cb2-df0d-41c3-885c-b7006a856d3b"),
                            ProductName = "Handcrafted Cotton Chips",
                            Status = 0,
                            UnitPrice = 286.40m,
                            UnitsInStock = (short)9685
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6966),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("82f26339-c74d-436c-aeec-8c832b668e6d"),
                            ProductName = "Licensed Concrete Tuna",
                            Status = 0,
                            UnitPrice = 28.89m,
                            UnitsInStock = (short)8462
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6980),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("66f23178-7ba2-4667-bdf3-369397cb3b26"),
                            ProductName = "Incredible Plastic Soap",
                            Status = 0,
                            UnitPrice = 683.03m,
                            UnitsInStock = (short)8795
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(6994),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("8b959bfc-a456-4eaa-a8f8-aefd993eb5d6"),
                            ProductName = "Incredible Steel Table",
                            Status = 0,
                            UnitPrice = 978.37m,
                            UnitsInStock = (short)2361
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7008),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("a7138a90-0743-4be3-9901-fee0bcd7a2dd"),
                            ProductName = "Intelligent Concrete Keyboard",
                            Status = 0,
                            UnitPrice = 145.59m,
                            UnitsInStock = (short)3332
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7021),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("9d479782-becc-4ffb-8bec-c9dc87aa26d8"),
                            ProductName = "Ergonomic Fresh Bike",
                            Status = 0,
                            UnitPrice = 262.72m,
                            UnitsInStock = (short)8337
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7035),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("6444abef-3a12-4f09-aa1c-4c170e847827"),
                            ProductName = "Fantastic Fresh Computer",
                            Status = 0,
                            UnitPrice = 886.26m,
                            UnitsInStock = (short)94
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7050),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("0106f1e5-dbfb-4f9b-b8f0-b7a8f089f8c5"),
                            ProductName = "Gorgeous Wooden Mouse",
                            Status = 0,
                            UnitPrice = 887.21m,
                            UnitsInStock = (short)4595
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7088),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("efaa9b35-19e3-4c37-9420-4622077f7edc"),
                            ProductName = "Refined Granite Chicken",
                            Status = 0,
                            UnitPrice = 139.27m,
                            UnitsInStock = (short)4500
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7105),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("d559b041-6c19-49c4-875f-5a48309a1f13"),
                            ProductName = "Ergonomic Frozen Shirt",
                            Status = 0,
                            UnitPrice = 248.92m,
                            UnitsInStock = (short)4825
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7118),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("60d97d64-5b82-40d0-aca3-49274958612b"),
                            ProductName = "Incredible Frozen Ball",
                            Status = 0,
                            UnitPrice = 619.69m,
                            UnitsInStock = (short)3010
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7132),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("be3e6b81-1eee-437c-87b3-11eeddc85930"),
                            ProductName = "Ergonomic Granite Bacon",
                            Status = 0,
                            UnitPrice = 355.38m,
                            UnitsInStock = (short)5549
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7146),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("27642bc8-c607-4bb2-bd24-19585f8de8ed"),
                            ProductName = "Ergonomic Rubber Salad",
                            Status = 0,
                            UnitPrice = 381.88m,
                            UnitsInStock = (short)4070
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7159),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("2061d084-6b16-4893-aa67-1338d3a6048c"),
                            ProductName = "Unbranded Soft Bacon",
                            Status = 0,
                            UnitPrice = 954.86m,
                            UnitsInStock = (short)5284
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7173),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("7dfa28f7-0f1a-4cb1-8c05-7f082935f784"),
                            ProductName = "Incredible Soft Soap",
                            Status = 0,
                            UnitPrice = 204.67m,
                            UnitsInStock = (short)5878
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7187),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("1934f49f-5b6e-4cfc-bdc4-3f1cd58bec23"),
                            ProductName = "Handmade Frozen Bacon",
                            Status = 0,
                            UnitPrice = 808.91m,
                            UnitsInStock = (short)2945
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7201),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("5b5c2cd0-c3df-403d-8d9d-434bddb917cb"),
                            ProductName = "Handmade Fresh Computer",
                            Status = 0,
                            UnitPrice = 24.22m,
                            UnitsInStock = (short)3850
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7216),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("b4790f10-3ac9-4446-b79b-431894d4c5b4"),
                            ProductName = "Gorgeous Cotton Soap",
                            Status = 0,
                            UnitPrice = 447.55m,
                            UnitsInStock = (short)343
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7255),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("50523a17-99c7-482b-bc02-3986f183633d"),
                            ProductName = "Sleek Cotton Keyboard",
                            Status = 0,
                            UnitPrice = 403.29m,
                            UnitsInStock = (short)64
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7269),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("4e60ae5b-8621-410b-a734-fa9c33769bc5"),
                            ProductName = "Licensed Wooden Cheese",
                            Status = 0,
                            UnitPrice = 147.71m,
                            UnitsInStock = (short)7905
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7283),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("aa20ac0e-a70d-4829-be4e-330eedd59f9c"),
                            ProductName = "Generic Soft Chips",
                            Status = 0,
                            UnitPrice = 51.54m,
                            UnitsInStock = (short)8281
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7297),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("5443829b-91cc-421b-840f-253528a9a245"),
                            ProductName = "Handcrafted Cotton Table",
                            Status = 0,
                            UnitPrice = 427.72m,
                            UnitsInStock = (short)667
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7310),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("600fc7fc-ccde-47c1-8e51-a4ebf1b6ddc3"),
                            ProductName = "Fantastic Rubber Cheese",
                            Status = 0,
                            UnitPrice = 236.07m,
                            UnitsInStock = (short)2676
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7324),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("7e987a21-3a24-4869-bb76-ab64b32196aa"),
                            ProductName = "Handmade Metal Gloves",
                            Status = 0,
                            UnitPrice = 308.21m,
                            UnitsInStock = (short)3988
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7337),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("291a62d5-b3a9-4434-96ea-3b8675cee99a"),
                            ProductName = "Small Soft Chair",
                            Status = 0,
                            UnitPrice = 393.48m,
                            UnitsInStock = (short)3352
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7353),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("a48c05fc-6e49-4dde-aea9-43970224f57d"),
                            ProductName = "Gorgeous Plastic Salad",
                            Status = 0,
                            UnitPrice = 118.19m,
                            UnitsInStock = (short)8032
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7366),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("4ca6220c-0fd3-4873-91fb-dda6c0afa472"),
                            ProductName = "Fantastic Cotton Soap",
                            Status = 0,
                            UnitPrice = 799.49m,
                            UnitsInStock = (short)5265
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7380),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("4bd1eede-c672-4827-b6f3-e7832ba4001f"),
                            ProductName = "Fantastic Granite Shoes",
                            Status = 0,
                            UnitPrice = 319.27m,
                            UnitsInStock = (short)8492
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7420),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("6fcbbf4c-7e6e-471d-abe6-6471875b9af7"),
                            ProductName = "Intelligent Rubber Pants",
                            Status = 0,
                            UnitPrice = 976.11m,
                            UnitsInStock = (short)6718
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7434),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("469a816c-88a8-4805-9a22-ff2913992752"),
                            ProductName = "Tasty Frozen Ball",
                            Status = 0,
                            UnitPrice = 410.48m,
                            UnitsInStock = (short)5580
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7447),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("6b6cb8bc-f139-4cd6-968d-a4c234d1877b"),
                            ProductName = "Generic Frozen Salad",
                            Status = 0,
                            UnitPrice = 656.91m,
                            UnitsInStock = (short)4617
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7460),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("3cdd3ba9-ce11-4802-a936-edc6b34c9c02"),
                            ProductName = "Handcrafted Cotton Gloves",
                            Status = 0,
                            UnitPrice = 525.22m,
                            UnitsInStock = (short)3563
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7474),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("53e39093-5c96-4e81-bae0-cc8c832ef9ab"),
                            ProductName = "Ergonomic Steel Pizza",
                            Status = 0,
                            UnitPrice = 98.21m,
                            UnitsInStock = (short)943
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 4, 24, 950, DateTimeKind.Local).AddTicks(7489),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("7d151d24-d84c-4742-a88a-d8337bc371d0"),
                            ProductName = "Rustic Plastic Ball",
                            Status = 0,
                            UnitPrice = 37.89m,
                            UnitsInStock = (short)5610
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Product", b =>
                {
                    b.HasOne("ECommerce.Entity.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
