// <auto-generated />
using System;
using ECommerce.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.MVC.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    partial class ECommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Entity.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MasterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 676, DateTimeKind.Local).AddTicks(9997),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Electronics description.",
                            MasterID = new Guid("91974cce-d4e4-4c53-998a-19fdc549603c"),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Beauty",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(76),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Beauty description.",
                            MasterID = new Guid("729db11a-dd62-42d4-9b2a-75bd3a0e2c84"),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Automotive",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(79),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Automotive description.",
                            MasterID = new Guid("2e77a78c-647c-4ba0-b56e-e590a7b9b669"),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Home",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(82),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Home description.",
                            MasterID = new Guid("c50b5a7b-27ab-4adc-8cc1-5b3b0b9e53c3"),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Books",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(84),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Books description.",
                            MasterID = new Guid("5e35f5e8-e363-443d-bdfb-19c66a70c81e"),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Computers",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(109),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Computers description.",
                            MasterID = new Guid("70c9d09b-6126-4764-ac0f-fb4549cc2af6"),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Outdoors",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(112),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Outdoors description.",
                            MasterID = new Guid("6bf0cc03-1296-4dd6-a844-28dd78cca9fe"),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Beauty",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(115),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Beauty description.",
                            MasterID = new Guid("89e991b5-326d-4d7e-a403-1e4377c230a3"),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Tools",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(127),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tools description.",
                            MasterID = new Guid("c0ea52ea-5407-41b5-8b1a-1cb03b438d58"),
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Shoes",
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(131),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Shoes description.",
                            MasterID = new Guid("de5db860-a040-4570-a2b8-6da251c679c7"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("MasterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(268),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("b863c4aa-2e7e-46db-9a37-4fb111e9d2b6"),
                            ProductName = "Incredible Fresh Gloves",
                            Status = 0,
                            UnitPrice = 776.26m,
                            UnitsInStock = (short)6521
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(406),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("4e659864-497c-44c2-a190-90433fbb46fb"),
                            ProductName = "Unbranded Granite Bike",
                            Status = 0,
                            UnitPrice = 869.47m,
                            UnitsInStock = (short)9953
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(431),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("6c09b794-d9a3-4a5c-a240-5206d9bd1fa3"),
                            ProductName = "Handcrafted Soft Soap",
                            Status = 0,
                            UnitPrice = 615.85m,
                            UnitsInStock = (short)1512
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(452),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("5e45de56-f4cd-4cc7-9676-b26b714fa860"),
                            ProductName = "Awesome Plastic Gloves",
                            Status = 0,
                            UnitPrice = 312.61m,
                            UnitsInStock = (short)2918
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(471),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("d094f0fd-6573-4d11-8552-13b0fa28c210"),
                            ProductName = "Fantastic Steel Shoes",
                            Status = 0,
                            UnitPrice = 15.51m,
                            UnitsInStock = (short)6010
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(491),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("25508abb-aea9-41b1-bb9f-6d110ee3398e"),
                            ProductName = "Small Metal Chicken",
                            Status = 0,
                            UnitPrice = 301.64m,
                            UnitsInStock = (short)1418
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(513),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("791b6722-266e-4e6d-ac1c-7ce34246abce"),
                            ProductName = "Gorgeous Frozen Ball",
                            Status = 0,
                            UnitPrice = 465.24m,
                            UnitsInStock = (short)6521
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(532),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("359abf6c-9773-4afd-9dbd-3c05edd028bb"),
                            ProductName = "Generic Rubber Computer",
                            Status = 0,
                            UnitPrice = 102.46m,
                            UnitsInStock = (short)1070
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(575),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("4b5f1ad9-c645-4a0f-9f9c-d146b5de3436"),
                            ProductName = "Practical Fresh Cheese",
                            Status = 0,
                            UnitPrice = 435.32m,
                            UnitsInStock = (short)917
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(595),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("53dc2a42-c820-4fd4-b7e2-b2b4a54a7de2"),
                            ProductName = "Licensed Cotton Tuna",
                            Status = 0,
                            UnitPrice = 318.83m,
                            UnitsInStock = (short)8919
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(614),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("ecd3b773-06f5-45f4-996e-427a44fc1433"),
                            ProductName = "Ergonomic Frozen Towels",
                            Status = 0,
                            UnitPrice = 587.57m,
                            UnitsInStock = (short)5999
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(632),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handmade",
                            MasterID = new Guid("c4723e37-e502-4ae6-bd6a-91c0ebfb09fb"),
                            ProductName = "Tasty Granite Computer",
                            Status = 0,
                            UnitPrice = 479.78m,
                            UnitsInStock = (short)3610
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(648),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("bffdc0ce-1420-4646-b571-f38ec675c70a"),
                            ProductName = "Rustic Concrete Chicken",
                            Status = 0,
                            UnitPrice = 331.63m,
                            UnitsInStock = (short)8599
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(665),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("aeb8d450-ba46-4c42-8ec7-77cc453822af"),
                            ProductName = "Awesome Plastic Towels",
                            Status = 0,
                            UnitPrice = 938.53m,
                            UnitsInStock = (short)78
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(684),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("748d3b77-48a2-435a-8301-80c4212e117f"),
                            ProductName = "Incredible Metal Hat",
                            Status = 0,
                            UnitPrice = 628.01m,
                            UnitsInStock = (short)8345
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(702),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("eedc45b3-9a50-431d-85e0-33350d61426e"),
                            ProductName = "Practical Metal Tuna",
                            Status = 0,
                            UnitPrice = 31.27m,
                            UnitsInStock = (short)2028
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(719),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("21c717d6-33d4-4866-82ee-17c2577e2e9e"),
                            ProductName = "Sleek Rubber Chair",
                            Status = 0,
                            UnitPrice = 976.48m,
                            UnitsInStock = (short)5344
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(759),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("eeee8f72-6081-4fbe-8c13-bbf3e23344a5"),
                            ProductName = "Tasty Plastic Table",
                            Status = 0,
                            UnitPrice = 514.68m,
                            UnitsInStock = (short)2674
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(779),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("35eb5f07-5f03-4f90-930a-3a1d788d38f5"),
                            ProductName = "Tasty Rubber Bike",
                            Status = 0,
                            UnitPrice = 225.23m,
                            UnitsInStock = (short)1409
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(796),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("ec35e6d1-a747-4fbf-9024-e93f82b190e8"),
                            ProductName = "Generic Plastic Shoes",
                            Status = 0,
                            UnitPrice = 686.00m,
                            UnitsInStock = (short)9188
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(815),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("4f8811f7-e009-471f-b015-7814034e6cec"),
                            ProductName = "Handmade Fresh Gloves",
                            Status = 0,
                            UnitPrice = 519.34m,
                            UnitsInStock = (short)3867
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(833),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("f4c18886-2522-4b82-a024-719fb40eabef"),
                            ProductName = "Unbranded Frozen Soap",
                            Status = 0,
                            UnitPrice = 455.28m,
                            UnitsInStock = (short)4567
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(851),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("b672a78d-ab72-438a-809e-207909959c5f"),
                            ProductName = "Small Steel Mouse",
                            Status = 0,
                            UnitPrice = 749.79m,
                            UnitsInStock = (short)5300
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(868),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("6d74cd2e-8047-4ec2-8178-5a58ea5fd6fb"),
                            ProductName = "Practical Plastic Pizza",
                            Status = 0,
                            UnitPrice = 492.15m,
                            UnitsInStock = (short)3187
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(886),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("05de8da3-9b39-4052-bc51-33d9ccd4e341"),
                            ProductName = "Refined Rubber Hat",
                            Status = 0,
                            UnitPrice = 321.06m,
                            UnitsInStock = (short)7290
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(903),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("70e26e44-671b-40ac-947b-60b7d05e553c"),
                            ProductName = "Incredible Frozen Mouse",
                            Status = 0,
                            UnitPrice = 778.55m,
                            UnitsInStock = (short)122
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(919),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("3bfcbfd5-ea13-41a3-9581-b90bcea50989"),
                            ProductName = "Ergonomic Rubber Shoes",
                            Status = 0,
                            UnitPrice = 792.62m,
                            UnitsInStock = (short)485
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(955),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("c058b2ae-69bb-48cc-aee9-3b25ceda7c4e"),
                            ProductName = "Awesome Concrete Bike",
                            Status = 0,
                            UnitPrice = 42.83m,
                            UnitsInStock = (short)883
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(972),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("4fb7bc1a-496d-4bb4-99e3-633bed87f67b"),
                            ProductName = "Ergonomic Granite Mouse",
                            Status = 0,
                            UnitPrice = 604.02m,
                            UnitsInStock = (short)7886
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(989),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("db8e9941-b14f-40bc-8513-76642835570e"),
                            ProductName = "Unbranded Wooden Ball",
                            Status = 0,
                            UnitPrice = 626.17m,
                            UnitsInStock = (short)3575
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1009),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("d94bf42f-1414-430c-993e-ebf134cd77aa"),
                            ProductName = "Generic Rubber Bacon",
                            Status = 0,
                            UnitPrice = 625.18m,
                            UnitsInStock = (short)2520
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1026),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("93993e2f-593a-408f-8514-556a6b52cedf"),
                            ProductName = "Handmade Steel Car",
                            Status = 0,
                            UnitPrice = 670.47m,
                            UnitsInStock = (short)7501
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1043),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("44a34cde-cc7e-4063-bfc0-29bffe2f802a"),
                            ProductName = "Gorgeous Wooden Towels",
                            Status = 0,
                            UnitPrice = 596.38m,
                            UnitsInStock = (short)5686
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1061),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("33d072f3-20d1-4412-878d-f8fe0a026f11"),
                            ProductName = "Tasty Granite Sausages",
                            Status = 0,
                            UnitPrice = 659.28m,
                            UnitsInStock = (short)7627
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1079),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("9d4276a2-f399-4531-a281-bb4b27caec4f"),
                            ProductName = "Tasty Fresh Car",
                            Status = 0,
                            UnitPrice = 596.06m,
                            UnitsInStock = (short)8938
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1095),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("3f88b35b-e0a0-4bb9-9f68-5e4cee554a21"),
                            ProductName = "Gorgeous Frozen Shirt",
                            Status = 0,
                            UnitPrice = 813.99m,
                            UnitsInStock = (short)1897
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1113),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("a768b990-2d49-4234-a666-58c7e8c331ef"),
                            ProductName = "Small Granite Pants",
                            Status = 0,
                            UnitPrice = 839.88m,
                            UnitsInStock = (short)5647
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1165),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handmade",
                            MasterID = new Guid("95eb3f46-37be-457d-8db1-3a99fab9d333"),
                            ProductName = "Refined Soft Chicken",
                            Status = 0,
                            UnitPrice = 248.48m,
                            UnitsInStock = (short)3752
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1184),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("9a429f1f-13bd-48a8-92cb-b6b94bd6f556"),
                            ProductName = "Handmade Rubber Table",
                            Status = 0,
                            UnitPrice = 266.70m,
                            UnitsInStock = (short)5827
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1201),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("f9b1d55e-d961-43d8-9d62-e8a6dc8bead6"),
                            ProductName = "Licensed Fresh Computer",
                            Status = 0,
                            UnitPrice = 77.75m,
                            UnitsInStock = (short)2551
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1218),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("27ffbda7-d339-4112-872a-0a86e20498f6"),
                            ProductName = "Incredible Cotton Salad",
                            Status = 0,
                            UnitPrice = 897.14m,
                            UnitsInStock = (short)5985
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1235),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("241af248-1acc-43d8-a0c1-f6ee2c32bad2"),
                            ProductName = "Sleek Soft Keyboard",
                            Status = 0,
                            UnitPrice = 576.85m,
                            UnitsInStock = (short)3952
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1252),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("4d814088-a518-4318-93d0-de86b350187a"),
                            ProductName = "Handcrafted Rubber Computer",
                            Status = 0,
                            UnitPrice = 655.15m,
                            UnitsInStock = (short)627
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1268),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("2867b9e4-951d-4b94-a1d8-1e4d7989b473"),
                            ProductName = "Gorgeous Plastic Computer",
                            Status = 0,
                            UnitPrice = 370.21m,
                            UnitsInStock = (short)3199
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1285),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("44569646-922a-40df-baf1-5f07cac13088"),
                            ProductName = "Handmade Metal Keyboard",
                            Status = 0,
                            UnitPrice = 202.16m,
                            UnitsInStock = (short)2387
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1301),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("4aa6829f-9260-469f-bb6d-e1fffaa7a42a"),
                            ProductName = "Sleek Steel Shoes",
                            Status = 0,
                            UnitPrice = 721.68m,
                            UnitsInStock = (short)5981
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1319),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("614abfe0-b92d-4993-b06a-ba50fb556be9"),
                            ProductName = "Ergonomic Frozen Mouse",
                            Status = 0,
                            UnitPrice = 938.39m,
                            UnitsInStock = (short)7582
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1356),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("486d1041-27c0-4dd0-98cc-b0663bfa7730"),
                            ProductName = "Small Fresh Cheese",
                            Status = 0,
                            UnitPrice = 619.15m,
                            UnitsInStock = (short)3254
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1372),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Fantastic",
                            MasterID = new Guid("61c92957-d739-4a46-b64b-8ba90ef0fc86"),
                            ProductName = "Incredible Steel Gloves",
                            Status = 0,
                            UnitPrice = 755.84m,
                            UnitsInStock = (short)6215
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1388),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("89234bdc-bb36-4321-ac2f-592c3b547c77"),
                            ProductName = "Handmade Concrete Tuna",
                            Status = 0,
                            UnitPrice = 840.42m,
                            UnitsInStock = (short)8527
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1404),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("e4a91a56-9d96-4951-86cc-a8b479294d23"),
                            ProductName = "Unbranded Soft Car",
                            Status = 0,
                            UnitPrice = 915.79m,
                            UnitsInStock = (short)3943
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1421),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("aa625e2a-2537-4fa9-8651-9d014c448c11"),
                            ProductName = "Handmade Concrete Table",
                            Status = 0,
                            UnitPrice = 540.56m,
                            UnitsInStock = (short)250
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1436),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("cbbd7871-c672-4b2b-8471-5f727d27c41e"),
                            ProductName = "Sleek Plastic Gloves",
                            Status = 0,
                            UnitPrice = 972.29m,
                            UnitsInStock = (short)501
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1452),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("e0ba8dd6-30c2-4e85-807b-6566ff5aa521"),
                            ProductName = "Refined Steel Chair",
                            Status = 0,
                            UnitPrice = 560.12m,
                            UnitsInStock = (short)6764
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1470),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("3617300a-7f1a-4e73-b66c-48975e4daa26"),
                            ProductName = "Generic Cotton Shirt",
                            Status = 0,
                            UnitPrice = 22.98m,
                            UnitsInStock = (short)7460
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1487),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("70493b29-a1b2-4b14-a683-753d87c1c050"),
                            ProductName = "Refined Metal Chips",
                            Status = 0,
                            UnitPrice = 13.90m,
                            UnitsInStock = (short)6407
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1504),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("345a5f6e-b486-4663-9da0-fc0bc3cf4709"),
                            ProductName = "Incredible Cotton Fish",
                            Status = 0,
                            UnitPrice = 138.53m,
                            UnitsInStock = (short)2263
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1542),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("8ccc6c52-4c26-489a-8621-98bf1fa0cdab"),
                            ProductName = "Awesome Wooden Chair",
                            Status = 0,
                            UnitPrice = 948.44m,
                            UnitsInStock = (short)1102
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1558),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Tasty",
                            MasterID = new Guid("b3d6cc73-c839-4216-907e-bf5556b7c545"),
                            ProductName = "Rustic Steel Cheese",
                            Status = 0,
                            UnitPrice = 728.22m,
                            UnitsInStock = (short)3882
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1573),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("2d74f722-236f-40bb-9850-f07ef7391365"),
                            ProductName = "Intelligent Concrete Bacon",
                            Status = 0,
                            UnitPrice = 591.09m,
                            UnitsInStock = (short)5560
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1590),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("61af9b8c-c916-4720-b421-784f832ff23c"),
                            ProductName = "Incredible Soft Chair",
                            Status = 0,
                            UnitPrice = 360.09m,
                            UnitsInStock = (short)3523
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1606),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("d7f14950-9909-4396-819b-650c9ea061d1"),
                            ProductName = "Intelligent Metal Chicken",
                            Status = 0,
                            UnitPrice = 415.38m,
                            UnitsInStock = (short)4678
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1625),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("658092b6-1e18-4f1f-9d3c-52c6e2901229"),
                            ProductName = "Fantastic Cotton Towels",
                            Status = 0,
                            UnitPrice = 534.94m,
                            UnitsInStock = (short)7146
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1642),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("94758869-fe52-4cc2-964c-6b80a5c26092"),
                            ProductName = "Rustic Granite Bike",
                            Status = 0,
                            UnitPrice = 539.67m,
                            UnitsInStock = (short)5091
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1659),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("0a2501fa-a5c9-46ce-96cc-408d3d8a7578"),
                            ProductName = "Sleek Frozen Mouse",
                            Status = 0,
                            UnitPrice = 909.67m,
                            UnitsInStock = (short)7743
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1698),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("556e5f60-f74b-4412-bf9f-b9b2f7e22cfd"),
                            ProductName = "Generic Fresh Tuna",
                            Status = 0,
                            UnitPrice = 931.81m,
                            UnitsInStock = (short)9983
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1717),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("86e474f3-665a-4539-a347-4ff7ebbfdfc6"),
                            ProductName = "Ergonomic Soft Car",
                            Status = 0,
                            UnitPrice = 700.46m,
                            UnitsInStock = (short)5448
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1735),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("f9e01207-d395-4042-aafe-63d6b79205eb"),
                            ProductName = "Handmade Frozen Pants",
                            Status = 0,
                            UnitPrice = 267.41m,
                            UnitsInStock = (short)6400
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1751),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("8b256d20-956a-4426-b8a1-a8776fac2597"),
                            ProductName = "Licensed Fresh Hat",
                            Status = 0,
                            UnitPrice = 605.79m,
                            UnitsInStock = (short)9026
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1768),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("d4ef796e-a397-42d6-a243-0298179b0dd1"),
                            ProductName = "Small Steel Salad",
                            Status = 0,
                            UnitPrice = 374.28m,
                            UnitsInStock = (short)1558
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1787),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("ab1c3ea4-c762-41ab-9872-fbd79db8f7e2"),
                            ProductName = "Unbranded Frozen Hat",
                            Status = 0,
                            UnitPrice = 649.89m,
                            UnitsInStock = (short)2701
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1803),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Ergonomic",
                            MasterID = new Guid("0da53bcc-5e62-46e1-b552-fdc941ae1de4"),
                            ProductName = "Sleek Cotton Hat",
                            Status = 0,
                            UnitPrice = 435.20m,
                            UnitsInStock = (short)7023
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1820),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("cab55d4b-eb63-4cb3-a174-b777800f04da"),
                            ProductName = "Handmade Steel Car",
                            Status = 0,
                            UnitPrice = 771.54m,
                            UnitsInStock = (short)139
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1835),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("251e5cf3-edaf-4b2a-9ec8-da2acfaec574"),
                            ProductName = "Awesome Steel Towels",
                            Status = 0,
                            UnitPrice = 44.33m,
                            UnitsInStock = (short)7226
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1851),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("55ed92a2-7d14-4bcd-b3d4-2802a07a1773"),
                            ProductName = "Intelligent Granite Bike",
                            Status = 0,
                            UnitPrice = 321.50m,
                            UnitsInStock = (short)5295
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1888),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("b4d1080b-1c38-4480-a325-0919e3f0238d"),
                            ProductName = "Awesome Metal Ball",
                            Status = 0,
                            UnitPrice = 785.60m,
                            UnitsInStock = (short)5745
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1906),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Incredible",
                            MasterID = new Guid("b7335755-dd50-43d8-9e21-cce767563524"),
                            ProductName = "Rustic Steel Keyboard",
                            Status = 0,
                            UnitPrice = 93.00m,
                            UnitsInStock = (short)4664
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1922),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("9c51bd65-c11a-4cbe-96eb-12a824323dad"),
                            ProductName = "Refined Steel Salad",
                            Status = 0,
                            UnitPrice = 24.99m,
                            UnitsInStock = (short)2131
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1940),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("0dc3598a-1f33-4858-a454-5428d5da0486"),
                            ProductName = "Sleek Cotton Computer",
                            Status = 0,
                            UnitPrice = 973.59m,
                            UnitsInStock = (short)3173
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 8,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1957),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("2aed93ad-921d-452a-894e-a05d15976f70"),
                            ProductName = "Fantastic Granite Keyboard",
                            Status = 0,
                            UnitPrice = 269.75m,
                            UnitsInStock = (short)9783
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1974),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("fbfe24cc-5fa7-4154-bd8d-f21368766c4e"),
                            ProductName = "Generic Plastic Chair",
                            Status = 0,
                            UnitPrice = 127.87m,
                            UnitsInStock = (short)8041
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(1990),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Intelligent",
                            MasterID = new Guid("713f1613-2519-469a-afa5-baf9e711a984"),
                            ProductName = "Handcrafted Wooden Chair",
                            Status = 0,
                            UnitPrice = 596.44m,
                            UnitsInStock = (short)1482
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2007),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Sleek",
                            MasterID = new Guid("6b41648a-1d30-4a9d-814b-59230c4ec8f6"),
                            ProductName = "Rustic Fresh Soap",
                            Status = 0,
                            UnitPrice = 882.83m,
                            UnitsInStock = (short)6286
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2023),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("27f57eeb-dfe8-4444-9a00-065a37e04a7f"),
                            ProductName = "Sleek Granite Shoes",
                            Status = 0,
                            UnitPrice = 18.97m,
                            UnitsInStock = (short)478
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2040),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Small",
                            MasterID = new Guid("6ff0354a-769d-4f4e-88fe-4e38582d21fc"),
                            ProductName = "Licensed Soft Shoes",
                            Status = 0,
                            UnitPrice = 169.63m,
                            UnitsInStock = (short)6231
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2075),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("bb190316-0ce2-4168-ad32-4219cc2ec3c8"),
                            ProductName = "Small Concrete Cheese",
                            Status = 0,
                            UnitPrice = 131.26m,
                            UnitsInStock = (short)9916
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2094),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("71b351c7-51aa-4696-a2a3-685ca46f4454"),
                            ProductName = "Awesome Metal Ball",
                            Status = 0,
                            UnitPrice = 652.92m,
                            UnitsInStock = (short)7354
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2111),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("cead07df-48a3-41e1-b487-68c55b3a5d3a"),
                            ProductName = "Sleek Concrete Towels",
                            Status = 0,
                            UnitPrice = 822.16m,
                            UnitsInStock = (short)6452
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2127),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("e466a062-5b14-4fa8-b200-a7fd93972107"),
                            ProductName = "Fantastic Metal Fish",
                            Status = 0,
                            UnitPrice = 735.47m,
                            UnitsInStock = (short)4880
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2143),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("5b21d299-b4a6-460e-b83c-fd1ab4fee2f6"),
                            ProductName = "Incredible Soft Pants",
                            Status = 0,
                            UnitPrice = 87.18m,
                            UnitsInStock = (short)2803
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2159),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handcrafted",
                            MasterID = new Guid("1bdd5024-483b-4ed4-9bc4-1236d01cdad2"),
                            ProductName = "Small Soft Ball",
                            Status = 0,
                            UnitPrice = 366.46m,
                            UnitsInStock = (short)612
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2175),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Licensed",
                            MasterID = new Guid("282e4142-ac5d-4354-8ae8-c91369b9794b"),
                            ProductName = "Licensed Fresh Cheese",
                            Status = 0,
                            UnitPrice = 730.87m,
                            UnitsInStock = (short)8558
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2192),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Generic",
                            MasterID = new Guid("41ebce6e-8352-45ca-8204-0ce3c63d517b"),
                            ProductName = "Rustic Frozen Sausages",
                            Status = 0,
                            UnitPrice = 384.42m,
                            UnitsInStock = (short)6586
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2208),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Practical",
                            MasterID = new Guid("4178ea2b-862f-4ed6-aaa4-8801c7750194"),
                            ProductName = "Intelligent Rubber Computer",
                            Status = 0,
                            UnitPrice = 678.82m,
                            UnitsInStock = (short)2295
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2226),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Gorgeous",
                            MasterID = new Guid("24db758c-a108-4525-96e9-012a8661fc24"),
                            ProductName = "Awesome Frozen Chips",
                            Status = 0,
                            UnitPrice = 24.80m,
                            UnitsInStock = (short)7880
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2261),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Rustic",
                            MasterID = new Guid("eba0ef50-6f73-420d-8635-4d091f13e7cf"),
                            ProductName = "Tasty Wooden Pants",
                            Status = 0,
                            UnitPrice = 385.80m,
                            UnitsInStock = (short)7104
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2280),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Unbranded",
                            MasterID = new Guid("b5b92ae2-94f3-4a04-887e-af207e329911"),
                            ProductName = "Ergonomic Fresh Pants",
                            Status = 0,
                            UnitPrice = 245.65m,
                            UnitsInStock = (short)6836
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2297),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Handmade",
                            MasterID = new Guid("963c63ac-c3c4-4a3f-93a5-fc0a789127d5"),
                            ProductName = "Gorgeous Granite Chair",
                            Status = 0,
                            UnitPrice = 759.05m,
                            UnitsInStock = (short)1584
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2313),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Awesome",
                            MasterID = new Guid("68002253-94bc-4fd1-9d9e-34a4f75ae3d9"),
                            ProductName = "Small Frozen Chips",
                            Status = 0,
                            UnitPrice = 787.59m,
                            UnitsInStock = (short)8158
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-I9V1GOS",
                            CreatedDate = new DateTime(2023, 9, 7, 11, 8, 19, 677, DateTimeKind.Local).AddTicks(2329),
                            CreatedIpAddress = "192.161.1.1",
                            Description = "Refined",
                            MasterID = new Guid("460bf6c8-3a05-42e3-a92d-829fb123737c"),
                            ProductName = "Intelligent Cotton Chair",
                            Status = 0,
                            UnitPrice = 606.87m,
                            UnitsInStock = (short)910
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Product", b =>
                {
                    b.HasOne("ECommerce.Entity.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Entity.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
